// Code generated by MockGen. DO NOT EDIT.
// Source: payment.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/fajrinajiseno/mygolangapp/internal/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockPaymentUsecase is a mock of PaymentUsecase interface.
type MockPaymentUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentUsecaseMockRecorder
}

// MockPaymentUsecaseMockRecorder is the mock recorder for MockPaymentUsecase.
type MockPaymentUsecaseMockRecorder struct {
	mock *MockPaymentUsecase
}

// NewMockPaymentUsecase creates a new mock instance.
func NewMockPaymentUsecase(ctrl *gomock.Controller) *MockPaymentUsecase {
	mock := &MockPaymentUsecase{ctrl: ctrl}
	mock.recorder = &MockPaymentUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentUsecase) EXPECT() *MockPaymentUsecaseMockRecorder {
	return m.recorder
}

// ListPayment mocks base method.
func (m *MockPaymentUsecase) ListPayment(status, id, sortExpr string, limit, offset int) ([]*entity.Payment, *entity.PaymentSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPayment", status, id, sortExpr, limit, offset)
	ret0, _ := ret[0].([]*entity.Payment)
	ret1, _ := ret[1].(*entity.PaymentSummary)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListPayment indicates an expected call of ListPayment.
func (mr *MockPaymentUsecaseMockRecorder) ListPayment(status, id, sortExpr, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPayment", reflect.TypeOf((*MockPaymentUsecase)(nil).ListPayment), status, id, sortExpr, limit, offset)
}

// ReviewPayment mocks base method.
func (m *MockPaymentUsecase) ReviewPayment(ctx context.Context, id string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReviewPayment", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReviewPayment indicates an expected call of ReviewPayment.
func (mr *MockPaymentUsecaseMockRecorder) ReviewPayment(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReviewPayment", reflect.TypeOf((*MockPaymentUsecase)(nil).ReviewPayment), ctx, id)
}
