// Package openapigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package openapigen

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Error defines model for Error.
type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// PaginationMeta defines model for PaginationMeta.
type PaginationMeta struct {
	// Limit Limit or page size used
	Limit *int `json:"limit,omitempty"`

	// Offset Offset used
	Offset *int `json:"offset,omitempty"`

	// Total Total number of items
	Total *int `json:"total,omitempty"`
}

// Payment defines model for Payment.
type Payment struct {
	Amount    *string    `json:"amount,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Id        *string    `json:"id,omitempty"`
	Merchant  *string    `json:"merchant,omitempty"`
	Status    *string    `json:"status,omitempty"`
}

// PaymentSummary defines model for PaymentSummary.
type PaymentSummary struct {
	// Failed Total number of failed payment
	Failed *int `json:"failed,omitempty"`

	// Success Total number of success payment
	Success *int `json:"success,omitempty"`
}

// User defines model for User.
type User struct {
	Email *string `json:"email,omitempty"`
	Role  *string `json:"role,omitempty"`
	Token *string `json:"token,omitempty"`
}

// Limit defines model for limit.
type Limit = int

// Offset defines model for offset.
type Offset = int

// Sort defines model for sort.
type Sort = string

// ForbiddenError defines model for ForbiddenError.
type ForbiddenError = Error

// LoginResponse defines model for LoginResponse.
type LoginResponse = User

// NotFoundError defines model for NotFoundError.
type NotFoundError = Error

// PaymentListResponse defines model for PaymentListResponse.
type PaymentListResponse struct {
	Meta     *PaginationMeta `json:"meta,omitempty"`
	Payments *[]Payment      `json:"payments,omitempty"`
	Summary  *PaymentSummary `json:"summary,omitempty"`
}

// PaymentReviewResponse defines model for PaymentReviewResponse.
type PaymentReviewResponse struct {
	Message *string `json:"message,omitempty"`
}

// UnauthorizedError defines model for UnauthorizedError.
type UnauthorizedError = Error

// PostDashboardV1AuthLoginJSONBody defines parameters for PostDashboardV1AuthLogin.
type PostDashboardV1AuthLoginJSONBody struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// GetDashboardV1PaymentsParams defines parameters for GetDashboardV1Payments.
type GetDashboardV1PaymentsParams struct {
	// Limit Limit number of items to return (max 100)
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Offset from start (0-based)
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`

	// Sort Comma-separated sort fields. Common patterns: `-created_at` (prefix `-` = desc) `amount` (no prefix `-` = asc)
	Sort *Sort `form:"sort,omitempty" json:"sort,omitempty"`

	// Status status of payment (completed , processing , or failed)
	Status *string `form:"status,omitempty" json:"status,omitempty"`
}

// PostDashboardV1AuthLoginJSONRequestBody defines body for PostDashboardV1AuthLogin for application/json ContentType.
type PostDashboardV1AuthLoginJSONRequestBody PostDashboardV1AuthLoginJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login with email + password
	// (POST /dashboard/v1/auth/login)
	PostDashboardV1AuthLogin(w http.ResponseWriter, r *http.Request)
	// Allows marking a payment as reviewed only by operation role
	// (PUT /dashboard/v1/payment/{id}/review)
	PutDashboardV1PaymentIdReview(w http.ResponseWriter, r *http.Request, id string)
	// List of payments
	// (GET /dashboard/v1/payments)
	GetDashboardV1Payments(w http.ResponseWriter, r *http.Request, params GetDashboardV1PaymentsParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Login with email + password
// (POST /dashboard/v1/auth/login)
func (_ Unimplemented) PostDashboardV1AuthLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Allows marking a payment as reviewed only by operation role
// (PUT /dashboard/v1/payment/{id}/review)
func (_ Unimplemented) PutDashboardV1PaymentIdReview(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List of payments
// (GET /dashboard/v1/payments)
func (_ Unimplemented) GetDashboardV1Payments(w http.ResponseWriter, r *http.Request, params GetDashboardV1PaymentsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostDashboardV1AuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostDashboardV1AuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDashboardV1AuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutDashboardV1PaymentIdReview operation middleware
func (siw *ServerInterfaceWrapper) PutDashboardV1PaymentIdReview(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutDashboardV1PaymentIdReview(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDashboardV1Payments operation middleware
func (siw *ServerInterfaceWrapper) GetDashboardV1Payments(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDashboardV1PaymentsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", r.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDashboardV1Payments(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/dashboard/v1/auth/login", wrapper.PostDashboardV1AuthLogin)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/dashboard/v1/payment/{id}/review", wrapper.PutDashboardV1PaymentIdReview)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/dashboard/v1/payments", wrapper.GetDashboardV1Payments)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7RYW2/bNhT+KwfcHlJMieQmD4WAAcsuLTokXdG020MXLLR0bLMVSZWkkriB/vtwSNmS",
	"bHr22vTNIs/1O1f6gRVa1lqhcpblD6zmhkt0aPxXJaRw9KNEWxhRO6EVy9kFHYNq5BQN6BkIh9KC02DQ",
	"NUbBkeT3MMmyJyxhghg+NWiWLGGKS2R5JzZhtlig5EH+jDeVY/nTLGGS3wvZSJZPMvoSqvtKmFvWxC+U",
	"wzka1rYJ07OZxYiNf/hzmBktwTpuHBxlx1NusdxlVScpatbQjixqh9UmYsUvWkp+bJFgdVgCUcFMYFXa",
	"E6BLraDmzqFRNoeb48Ig0f3D3Q0c1QZn4h5ujm/gRyC5T+CGS90oulQaRvfcFk/+Vjtc88YNHcN7LuuK",
	"rgYq2dox64xQc9aSYwZtrZVFnxDPtZmKskT1mzHa0EmhlUPlXed1XYmCk+vpB0v+rxV55tmKmT5uedVg",
	"EFAiy8+y04RJtJbPyYC1nhyWuoFSg9IOFvwWoUYjhbVCK8o4XhRoLbiFsGDQ6sYUGOzunf3e4Izl7Lu0",
	"T/U03No0+OEZxpF7Z9GAsMAbt0DlyC8sYdo4bwmdaiM+Y8nahF3ouVBvOpwOAOUw08iCmGVdkTn9ERVw",
	"VULjTVUzbaTXQya90u65blT5jeP0SjuYkZ58jb7Hx589ShzeRMQm7DVfSlTuQlj3RbjXRtdonAgOS3R7",
	"DXzN50J5cZdE3SasDjZ4Cb4D7hfhGYi3qzNuDF/St22k5GZ5oISrjrrtJenpByxcDMCOBwirAXRv8Fbg",
	"3aOA1yXDsKtcNaEuL7n5CNxC0IZlpMX8DxeMlwIrjW3C3qm+Er8k1Rs1qm/v5yoU7JLajJqDpuq65ZUo",
	"Q9GxZLsqJsOqeDeWmoPcJekxKuS810VNccZFhSWpWmktDJZEwCvLen3e/zVm45gGrwYB9Q5uTr0kHvvD",
	"vY8lg8FPjTAUivfBjF7L9VaqUDaPynLLk//cYLSBms8RrPiM1EUpPdd+TLKYx3vWjcOEOO14tS3jLR1v",
	"rlVjafHdI4JK6DRbcIT1YRwvXokCf+q+Twott+OSsMGWECaEpF+s5A6PnZAY4xHlWNEkRiTRFAu+adNl",
	"dwrnMR7ruGvsmIMqpkKa0QnURlP3oZxLKMihJA7pPWvorvqGPEawk7U3eF0ZdkNif07Y0DH3C+4IY5LP",
	"DkwPv1lseYaSC5+VW3gbXWH0IpTx9k2kqSfMYtEY4ZZX1H6Cyilyg4YaWP/1fJVbv//1drWzkqRw2wdx",
	"4Vwd2iGtPt4I4ULyLF/oC67m53UN569fUrtGYwOak5PsJPOFXKPitWA5Oz3JTk4ZzXO38FalJbeLqeam",
	"TG8nKTWztKINz0OmrU9VAs63nZclDSht3a8rpj8n5JDfCVnoZ2jdz7pcfsWQ3R2bmlt7p00Zj8KwmwYZ",
	"A47r6OjtWZxpcPMB8DTLdg2qNV063ofbhJ1lk/1c27O8HW5GYcuGO+EW4F2BH2DtClGOw9aVR/ogyjYN",
	"i4OHtYmFrxlGr+sAL8uwtHjE+kfx+4fwwqJs6R9YomSbyA3n+mZgrr8E1fji9hXoEufpfs6NN59nO9vP",
	"Nn6BDBuAB3FY+u+vCZE+0udVpe8sSG4+Ug/nq15Hm6TpNknQqlrCdAnrUIJvUzszwQM9x0j4X2Ak/HY7",
	"7jF/e5I0rBptspew2yEOoPTvdqIbj4Qw/2gYrIA52j/+dv3t0Q3Tb5WuoyfaV7aCQ/OHdA7Qsd2ajeZ2",
	"FcrGVN0IydO00gWvFtq6/Fn2LGPtdftvAAAA//9Cw7sIFhMAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
