// Package openapigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package openapigen

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Error defines model for Error.
type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// PaginationMeta defines model for PaginationMeta.
type PaginationMeta struct {
	// Limit Limit or page size used
	Limit *int `json:"limit,omitempty"`

	// Offset Offset used
	Offset *int `json:"offset,omitempty"`

	// Total Total number of items
	Total *int `json:"total,omitempty"`
}

// Payment defines model for Payment.
type Payment struct {
	Amount    *string    `json:"amount,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Id        *string    `json:"id,omitempty"`
	Merchant  *string    `json:"merchant,omitempty"`
	Status    *string    `json:"status,omitempty"`
}

// PaymentSummary defines model for PaymentSummary.
type PaymentSummary struct {
	// Completed Total number of completed payment
	Completed *int `json:"completed,omitempty"`

	// Failed Total number of failed payment
	Failed *int `json:"failed,omitempty"`

	// Pending Total number of pending payment
	Pending *int `json:"pending,omitempty"`

	// Total Total all payment
	Total *int `json:"total,omitempty"`
}

// User defines model for User.
type User struct {
	Email *string `json:"email,omitempty"`
	Role  *string `json:"role,omitempty"`
	Token *string `json:"token,omitempty"`
}

// Limit defines model for limit.
type Limit = int

// Offset defines model for offset.
type Offset = int

// Sort defines model for sort.
type Sort = string

// ForbiddenError defines model for ForbiddenError.
type ForbiddenError = Error

// LoginResponse defines model for LoginResponse.
type LoginResponse = User

// NotFoundError defines model for NotFoundError.
type NotFoundError = Error

// PaymentListResponse defines model for PaymentListResponse.
type PaymentListResponse struct {
	Meta     *PaginationMeta `json:"meta,omitempty"`
	Payments *[]Payment      `json:"payments,omitempty"`
	Summary  *PaymentSummary `json:"summary,omitempty"`
}

// PaymentReviewResponse defines model for PaymentReviewResponse.
type PaymentReviewResponse struct {
	Message *string `json:"message,omitempty"`
}

// UnauthorizedError defines model for UnauthorizedError.
type UnauthorizedError = Error

// PostDashboardV1AuthLoginJSONBody defines parameters for PostDashboardV1AuthLogin.
type PostDashboardV1AuthLoginJSONBody struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// GetDashboardV1PaymentsParams defines parameters for GetDashboardV1Payments.
type GetDashboardV1PaymentsParams struct {
	// Limit Limit number of items to return (max 100)
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Offset from start (0-based)
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`

	// Sort Comma-separated sort fields. Common patterns: `-created_at` (prefix `-` = desc) `amount` (no prefix `-` = asc)
	Sort *Sort `form:"sort,omitempty" json:"sort,omitempty"`

	// Status status of payment (completed , processing , or failed)
	Status *string `form:"status,omitempty" json:"status,omitempty"`

	// Id payment id
	Id *string `form:"id,omitempty" json:"id,omitempty"`
}

// PostDashboardV1AuthLoginJSONRequestBody defines body for PostDashboardV1AuthLogin for application/json ContentType.
type PostDashboardV1AuthLoginJSONRequestBody PostDashboardV1AuthLoginJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login with email + password
	// (POST /dashboard/v1/auth/login)
	PostDashboardV1AuthLogin(w http.ResponseWriter, r *http.Request)
	// Allows marking a payment as reviewed only by operation role
	// (PUT /dashboard/v1/payment/{id}/review)
	PutDashboardV1PaymentIdReview(w http.ResponseWriter, r *http.Request, id string)
	// List of payments
	// (GET /dashboard/v1/payments)
	GetDashboardV1Payments(w http.ResponseWriter, r *http.Request, params GetDashboardV1PaymentsParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Login with email + password
// (POST /dashboard/v1/auth/login)
func (_ Unimplemented) PostDashboardV1AuthLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Allows marking a payment as reviewed only by operation role
// (PUT /dashboard/v1/payment/{id}/review)
func (_ Unimplemented) PutDashboardV1PaymentIdReview(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List of payments
// (GET /dashboard/v1/payments)
func (_ Unimplemented) GetDashboardV1Payments(w http.ResponseWriter, r *http.Request, params GetDashboardV1PaymentsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostDashboardV1AuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostDashboardV1AuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDashboardV1AuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutDashboardV1PaymentIdReview operation middleware
func (siw *ServerInterfaceWrapper) PutDashboardV1PaymentIdReview(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutDashboardV1PaymentIdReview(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDashboardV1Payments operation middleware
func (siw *ServerInterfaceWrapper) GetDashboardV1Payments(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDashboardV1PaymentsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", r.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "id" -------------

	err = runtime.BindQueryParameter("form", true, false, "id", r.URL.Query(), &params.Id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDashboardV1Payments(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/dashboard/v1/auth/login", wrapper.PostDashboardV1AuthLogin)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/dashboard/v1/payment/{id}/review", wrapper.PutDashboardV1PaymentIdReview)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/dashboard/v1/payments", wrapper.GetDashboardV1Payments)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7RYW2/bOBb+KwfcfUixSiQ3eSgELLDZmWnRQdIpmnbmoRNMaPHYZiuSKkklcQP/98Eh",
	"ZUuymdrTy5tFnut3rvQDq4xqjEbtHSsfWMMtV+jRhq9aKunph0BXWdl4aTQr2QUdg27VFC2YGUiPyoE3",
	"YNG3VsOR4vcwKYonLGOSGD61aJcsY5orZGUnNmOuWqDiUf6Mt7Vn5dMiY4rfS9UqVk4K+pK6+8qYXzbE",
	"L7XHOVq2WmXMzGYOEzb+Fs5hZo0C57n1cFQcT7lD8ZhVnaSkWUM7iqQdztiEFT8ZpfixQ4LVowCigpnE",
	"WrgToEujoeHeo9WuhJvjyiLR/cX9DRw1FmfyHm6Ob+C/QHKfwA1XptV0qQ2M7rmrnvypH3EtGDd0DO+5",
	"amq6GqhkG8ect1LP2Yocs+gaox2GhHhu7FQKgfoXa42lk8pojzq4zpumlhUn1/MPjvzfKArMszUzfdzy",
	"usUoQCArz4rTjCl0js/JgI2eEpamBWFAGw8LfovQoFXSOWk0ZRyvKnQO/EI6sOhMayuMdvfO/tvijJXs",
	"X3mf6nm8dXn0IzCMI/fOoQXpgLd+gdqTXyhg2vpgCZ0aKz+jYKuMXZi51G86nA4A5TDTyIKUZV2RefMR",
	"NXAtoA2m6pmxKughk14Z/9y0WvzgOL0yHmakp9ygH/AJZ98lDm8SYjP2mi8Van8hnf8q3BtrGrReRocV",
	"+r0GvuZzqYO4S6JeZayJNgQJoQPuFxEYiLerM24tX9K3a5XidnmghKuOetVLMtMPWPkUgB0PEFYD6N7g",
	"rcS77wJelwzDrnLVxrq85PYjcAdRG4pEi/kHLtggBdYaVxl7p/tK/JpUb/WovoOf61CwS2ozeg6GquuW",
	"11LEomPZblVMhlXxbiy1BPWYpO9RIee9LmqKMy5rFKRqrbWyKIiA1471+oL/G8zGMY1eDQIaHNyeelk6",
	"9od7n0oGi59aaSkU76MZvZbrnVShbB6V5Y4nX9xgjIWGzxGc/IzURSk9N35MipTHe9aNw4R443m9K+Mt",
	"HW+vVWNp6d0jgUrsNDtwxPVhHC9eywr/132fVEbtxiVjgy0hTghFv5jgHo+9VJjikWKsaJIiUmirBd+2",
	"6bI7hfMUj/Pct27MQRVTI83oDBprqPtQzmUU5FgSh/SeDXRXfUPeLo1Oz/749SZ1o2IYy6fJzOgs3Su6",
	"K/KE3HTGNagFubxXcEd4uOQv5jKv65SkswPTOGxAOxFAxWXQuJMX1tSYvIjtZvcmMXwy5rBqrfTLK2qT",
	"UeUUuUVLjbb/er6ugV//eLverUlSvO2TbeF9E9s2rWjBCOljki9fmAuu5+dNA+evX9JYQesifpOT4qQI",
	"DadBzRvJSnZ6UpycMto7/CJYlQvuFlPDrchvJzk13bymTTRAZlwoKQIutMeXggapcf7nNdPvE3Io7K4s",
	"9l10/v9GLL9hGXg8Ng137s5YkY7CsOtHGQOO6+SK0LN42+L2Q+VpUTw2UDd0+XhvX2XsrJjs59rdOVbD",
	"DS6+BuBO+gUEV+A/sHGFKMdh68ojf5BilccFJ8DapsLXDqPXdaqXIi5XAbH+8f7+Ib4EKVv6h6AUbBu5",
	"4f6xHZjrr0E1vWB+A7rEebqfc+ttGtjO9rONX0rDBhBAHJb++2tCpI/0eV2bOweK24/UM/m619HGa7uN",
	"F4yulzBdwiaUENrUo5kQgJ5jIvwvMBF+txv3lL89SR5XolW2l7DbdQ6gDP8vEN14CMQ5HcZKB8zR/jH9",
	"2N8z3dD/UrruGLBWG9I+JTRc/Jj8H71Nv7G3HJqQpHMAt+veF2hv17nR2rqbSWWe16bi9cI4Xz4rnhVs",
	"db36OwAA//90u1IKDxQAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
