// Code generated by MockGen. DO NOT EDIT.
// Source: payment.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	entity "github.com/fajrinajiseno/mygolangapp/internal/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockPaymentRepository is a mock of PaymentRepository interface.
type MockPaymentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentRepositoryMockRecorder
}

// MockPaymentRepositoryMockRecorder is the mock recorder for MockPaymentRepository.
type MockPaymentRepositoryMockRecorder struct {
	mock *MockPaymentRepository
}

// NewMockPaymentRepository creates a new mock instance.
func NewMockPaymentRepository(ctrl *gomock.Controller) *MockPaymentRepository {
	mock := &MockPaymentRepository{ctrl: ctrl}
	mock.recorder = &MockPaymentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentRepository) EXPECT() *MockPaymentRepositoryMockRecorder {
	return m.recorder
}

// GetPayments mocks base method.
func (m *MockPaymentRepository) GetPayments(status, sortExpr string, limit, offset int) ([]*entity.Payment, int, int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPayments", status, sortExpr, limit, offset)
	ret0, _ := ret[0].([]*entity.Payment)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(int)
	ret3, _ := ret[3].(int)
	ret4, _ := ret[4].(error)
	return ret0, ret1, ret2, ret3, ret4
}

// GetPayments indicates an expected call of GetPayments.
func (mr *MockPaymentRepositoryMockRecorder) GetPayments(status, sortExpr, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPayments", reflect.TypeOf((*MockPaymentRepository)(nil).GetPayments), status, sortExpr, limit, offset)
}

// Review mocks base method.
func (m *MockPaymentRepository) Review(id string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Review", id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Review indicates an expected call of Review.
func (mr *MockPaymentRepositoryMockRecorder) Review(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Review", reflect.TypeOf((*MockPaymentRepository)(nil).Review), id)
}
